### ISSUE TITLE
FEAT: Read Style property which specifies a CSS file

### ISSUE THREAD

**Issue by byronigoe** [darlanmendonca/package-files#1]
Some node modules specify "main" and "style" for the distribution JS and CSS respectively, instead of using "files". For example "npm install leaflet"

**Comment by darlanmendonca** [comment]
yeah, main is for .js, and style is a custom key, what dont be a wrong, but is custom, and dont exists in npm package documentation.

my intention on implement use of key `files`, is follow the npm documentation (https://docs.npmjs.com/files/package.json#files), instead create a custom key to store different types of files
